export default {
  games: [],
  selectedGame: null,
  selectedGameData: {},
  selectedPlayerCount: null,
  playersCash: [],
  players: [],
  corporationsWealth: [],
  playerCorporationOwnership: [],
  simulatedRounds: 0,
  advancedSimulation: false,
  checkAbove100Percentage: [],
  multipleShare: false,
  multipleShareSelected: [],
  showCorpHeaderMobile: false,
  focusedCorpIndex: 0,
};
