name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install --force
      - name: Build
        run: npm run build
      - name: Deploy with Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          # see via cmd: firebase login:ci
          FIREBASE_TOKEN: ${{ secrets.$FIREBASE_TOKEN }}